#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 黒龍の塔
** 0

   その身を腐らせながらも，その心は憎しみと諦めの相反する情動に支配されていた。
  
   最強の邪鬼でさえも断ち切る剣。しかし黒龍のはばたきは暴風となり，触れることすらかなわなかった。

   巨人が振るう棍棒でさえも傷ひとつつかぬ鎧。しかし黒龍の息吹がもつ毒は鎧の内にある肉を侵した。

   あまたの敵を打ち倒した自分には誇りがあった。魔神を滅ぼし，秘石を集め，聖獣の加護を受けた。

   黒龍がいかに強大であろうと渡りあえる。そう思っていた。

   そこに油断がなかったとはいえない。

   それほどまでに黒龍のみが圧倒的な超者だった。

   いつのまにか，視界の左右には頂上に至るまでに打ち倒した敵のなきがらが並んでいた。

   意思とは裏腹にその身体は黒龍に背を向け，生きようとしていたのだった。

   でもどこへ。

** 1

   戦士ミトが次に気づいたとき，見慣れた天井が目に入った。包帯だらけの上体を起こすと，その音に気づいたか，導師ケインが手製のロウソクを灯して現れた。ミトは目をそらした。ケインは何か言おうとしたが，一旦黙り，少しの時間をおいて口を開いた。

   「何か飲むか」

   ミトがうなずくと，ケインは部屋を出てから，すりつぶした薬草を混ぜた水を持ってきた。ミトはそれを針のような両手で受け取り，割れた口に含んだ。

   「何か焦げるような匂いがしてな。火事と思い家を出た。すると骨ばかりのお前が倒れておったのだよ」

   話を聞きながら，ミトは思うことを整理していた。

   「それにしても手ひどくやられたな。お前の剣を持ちあげたらすぐ粉々に割れてしまったよ」ケインは冗談のつもりで言った。だがそれはミトが心の内で認めつつも受け入れられないものだった。命の恩人であったことも忘れ，つかみかかろうとしたものの，身体は力なく揺らぎ，そのまま床に倒れこんだ。

   これがかつて祝福の騎士だった者のなれのはてか。

   ケインの謝る声，曲がった腰で自分を持ち上げようとする姿を遠くに感じながら，ミトは己の過去を思った。

** 2

   太陽が姿を消した日，黒龍が血の塔に現れた。光を失った世界にはやがて死が蔓延し，人々は終末が近づくのを感じた。ミトはその混乱に乗じ暴れまわった山賊団の一人だった。この世という場所に自分が形を持った日からどれくらい経つのかは覚えていない。だがこの世はミトから全てを奪った。だから奪い返してやるのだ。

   朽ちかけた教会を襲った日，一人の女に会った。その女を取り囲む者からは「聖女さま」と呼ばれていた。聖職者というものはこちらが刃物をちらつかせただけでそのたるみきった腹を揺らせ逃げ回るのが決まりだったが，その女だけはミトに憐れみに満ちたまなざしを向けた。

   「この方達に手を出さないのであれば，私はどうなっても構いません。ただ，その前に私の話を聞いていただけませんか」

   山賊になってからというもの，それはこれまで自分が見てきたどの目とも違っていた。「少しだけでも。どうかお願いします」

   ミトは武器をしまい，壊れかけた椅子に腰かけると，相手に促した。聖女と呼ばれる女は書物を取り出し，話をはじめた。周りの者はしゃがみ込み，鈴の鳴るような女の声に耳をすませた。

   不思議な時間であった。話はいつまでも続き，そしていつまでも聞いた。これまで感じたことのない心地良さであった。女の話から，ミトはこの世界には奪う者だけでなく与える者もいることを知った。そして弱き者を守り，善きことをなせば，最も慈悲深い者から祝福を授けられ，たとえ己が身の朽ちた後も平穏に包まれることを学んだ。その平穏を自分が得ることができるか問うた。女はゆっくりと頷いた。

   その日からミトは山賊を捨て，祝福の騎士として生きた。なぜ自分には力があるのか。世にはびこる邪悪を滅ぼし，その根源たる黒龍を討つためだ。ミトは文字が読めなかったため，言葉をとおして聖女に学んだ。その聖句を唱えると，自身の身体が光に満ち，どんな敵にも打ち勝った。やがて聖痕の刻まれた像を受け取った後は，隠者ケインに教えを受けた。祝福の騎士としての活躍をミトは誰に言うこともなかったが，名も知らぬ戦士の奮闘を人々は噂した。

   決戦の時が近づいていた。

** 3

   「ここはもう安全ではなくなった。都に向かいなさい」

   導師ケインの治療の甲斐もあり，ようやく一人で歩けるようになったばかりだった。ミトはどういうことかを身振りで尋ねた。

   「お前の命を狙う者がいる。ここに隠れていることもいずれわかるだろう。お前の代わりに手紙を書いておいたから，これを都のドブ街にいるロジャというお婆さんに渡すのだ。いいね」

   ケインがこれほど取り乱すのは初めてだった。そこからミトは容易ならぬ事態にあることを知り，師の言葉に従うことにした。山に入り，日々の鍛錬に使っていた小屋で支度をした。ぼろのクロークや，手入れは欠かさなかった鋼の剣。それらを身につけ，山を下る頃，何かの焼けるにおいを感じた。麓が赤く染まっている。

   導師が何者かに襲われたのだ。先の注意に従うならば，ここから一刻も早く離れなければならなかった。だが。

   「そこのお前。こんなところで何をしている。止まれ」

   ミトは何者かに呼びとめられた。鈍い色の鎧に身を固めた二人の兵士がこちらに近づいてくる。「聞こえているのか。ここで何をしているのだ。答えろ」

   ミトはフードで顔を隠したまま，えぐれた喉元を見せた。「ひっ」一人の兵士がたじろぐ。

   「山賊の頭がここに隠れていると知らせがあった。お前は何か知っているか」もう一人の兵士が言った。

   「貴様も山賊の仲間か」

   ミトは首をふった。

   「ならばここで何をしていたのだ。持っているものを見せろ」

   そう言われ，ミトは身にまとっていたぼろ布を落とした。「わっ」二人はあわてて目をそらした。それは突飛な行動によるものだけではない。兵士の目の前にあったのは，おそらくこれまでに見たなかで最も醜く，そして今後も見ることのないであろう姿だった。

   「もういい，早くどこかへ行け」一人の兵士にそう言われたミトは，再び布を身につけ，すぐにその場を離れた。ミトの姿に怯え，斬りかかってこなかったのは幸いだった。ただ他の仲間に知らされるのにそう時間はかからないだろう。相手はこの山には疎い。姿をくらますことは難しくなかった。

   ケインの下へ戻ることは敵の懐にとびこむようなものだ。それでも足は二人で過ごした小屋へと向かっていた。焦げるにおいが強まる。いったん道を外れ，林の中を進んだ。

   藪に隠れるようにしてあたりをうかがうと，かつて見慣れた小屋はそこにはなかった。かわりに黒い瓦礫が残り，ところどころで煙がくすぶっている。兵士の姿がいくつも見えた。そして瓦礫のなかに，槍先にかかげられた導師の首があった。

** 4
   
   都には，水晶の塔とよばれる，青白い光を放つ建造物がそびえたっていた。それは太陽を失ったこの世界において数少ない光の源であり，人々を支えていたのだ。その光をたよりに，ミトは都の教会にたどりついた。どの都であっても，街のなかでひときわ豪勢な建物があれば，それはきまって教会だったのだ。

   大扉をひらくと，中はわずかに明かりで照らされ，人々が祈りをささげていた。そのなかで僧侶とおぼしき者の視界に入り，挨拶をした。

   「ようこそわが教会へ。こちらへは初めてのようですが，なにかご用ですかな」相手は口元だけの笑顔で話しかけてくる。ミトは持っていた袋を渡すと，僧侶は怪訝な顔でそれを受け取った。そして中身を確認するやいなや，驚きとともに満面の笑みをうかべた。

   「なんと，この試練の時代にあって，これほど深い信仰をお持ちの方がいたとは。あなたはきっと(ザ…ザ…)に祝福されるでしょう」

   その後のミトへの感謝を含め，聞き取れない言葉があったが，文字を読める数少ない人間には違いない。ミトは懐から汚れた手紙を取り出し，中身を広げて見せた。

   僧侶はガーゼをのせた手でくしゃくしゃの手紙を受け取ると，その場で読みはじめた。なんらかの使者と考えたのだろう。だがまもなくその顔から笑顔が消えた。「失礼ですが，あなたはどなたですか。ここを訪れたのは何かの間違いでは…」

   ミトは首をふる。そして揺るぎない信仰の証として，胸から聖痕の刻まれた像を取り出して見せた。

   「じゃ，邪教徒っ」僧侶はひきつった顔で叫んだ。

   人々が一斉にミトを見る。それは昔，ミトが幾度も見た場面だった。

   『人殺しめ』『悪魔は殺せ』

   その言葉が放たれる前にミトは手紙を奪い取り教会を飛び出した。そしてそのままクロークをなびかせ光が届かない暗闇へ姿を消した。

** 5

   夢の中にいるようだった。

   下水の流れる格子の向こうでは何人もの兵士がたいまつをともし，都にまぎれこんだ悪魔を探し出そうと駆け回っている。その炎はミトの心に痛みをさす記憶を思い出させた。

   それは聖獣の試練を突破し，その加護を受け聖女たちの待つ教会に戻ってきた日のことだった。建物の中は荒らされ，天井まで赤く染まっていた。そこに身を寄せていたはずの者はズタズタにされ，誰彼の判別もつかない。なかでもひときわ激しく傷つけられた亡骸が壁にはりつけにされていた。衣服の類は当然のことながら剥かれていたが，爪のはがされたその指は見間違いようもなかった。

   かつてその指で本をなぞると，心の満たされる言葉がつむがれた。その指はミトの進むべき道をも示していた。だがその指はいまや何をさすこともなく，血のしずくを垂らしているのみだった。

   ミトは何日もかけ，一人一人の墓を作った。そのなかで，変色してはいるが聖女がまとっていた衣装と，教会に飾られていた最も慈悲深き者の像を見つけた。像は一部が砕け，刃による深い傷がついていたが，水で洗うとかつての輝きを感じさせた。
   
   聖女の衣装を一枚の布にすると，ミトはその身にまとった。そしてただ一人残った理解者である隠者ケインの下へ向かったのだ。

   「ミドさまとお見受けいたします」

   突然の声に，現実へ引き戻された。声がした方へ身構える。暗闇にうっすらと何かが立っている。

   「祝福の騎士ミドさま，導師ケインよりお話はうかがっております。どうぞこちらへ」

   そう言うと，声の主は奥へ消えた。見失うわけにはいかない。急いでミトは後を追った。

** 6   
   
   どれほど歩いただろうか。光のない暗闇を足音だけをたよりについていくと，ロウソクの明かりが灯る部屋に出た。そこには一脚の机があり，白髪で顔を隠した老婆がこちらと向かい合うように座っている。その服には見覚えがあった。導師ケインが身に付けていたものと同じ模様だ。
   
   「よくぞおいでくださいました，祝福の騎士殿。私はロジャと申します」

   ロジャ。その名前は一度だけ聞いた。そしてその人物に会うために都まで来たのだ。ミトは先のやりとりで端の少し破れた手紙を取り出し，老婆に渡した。

   手紙を手にした老婆はそれを机に広げ，しばらくうつむいたまま首だけを上下させていた。だが突如両手を机に叩きつけると，こちらをにらみつけ叫んだ。

   「祝福の騎士ミドよ」老婆のあまりの大声にうろたえた。「おまえにその名を捨て龍を滅する覚悟はあるか」
   
   龍を倒す。その言葉に胸が高鳴った。同時に，名を捨てるとはどういう意味か。事態が読めず，老婆の目を見返す。

   「闇の化身たる龍を滅するには，己が闇に染まらねばならぬ。それは狂気と修羅の道。
   
   最北の地，月の塔で真月の日に暗銀を打て。それは暗き盾となっておまえに縫いつき，龍の全てを退けるだろう。
   
   だがその誓いなくば，おまえの命は今ここで潰え，世界は龍のものとなる」

   その言葉とともに，ミトの背後から，幾人もの白装束を身にまとった者がぞろぞろと部屋に入ってきた。

   「龍を滅ぼす騎士がここに」白装束たちは叫んだ。

   「龍狩りの騎士よ。月の塔へ向かえ。そして龍を殺すのだ」

  <br>

  [[https://github.com/jamcha-aa/TowerofThem/blob/master/articles/02.md][後編へ進む]]

  <br>
  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
