#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 黒龍の塔
** 7
   太陽とともに月もその姿を消した。だがその魔力は，夜の続くこの世界にいまだ残っている。かつて新月と呼ばれた日，そして月の魔力が最も弱まる日，それが今では真月と呼ばれている。人のもつ憎しみ，恨み，つらみ，嫉妬，嘆き，光なきものが最も強まる時でもある。

   白装束の者に案内され都の下水道から出ると，ミトは託された暗銀の板を持ち，ロジャ選りすぐりの戦士達とともに月の塔を目指した。その間，都を行き来する者を狙う盗賊に幾度も襲われた。黒龍に会う前であれば何なく打ち倒せた敵だった。だがその力のほとんどは失われている。苦戦が続くなかで戦士は一人，また一人と倒れていき，やがて月の塔に着く頃にはミト一人だけになっていた。

   月の塔はどの街からも遠く離れ，訪れる者もない。閑散とした塔の内部は，かつての戦いの跡が，朽ちた鎧と風化した骨に残されているのみだ。塔の暗闇でミトは真月の日を待ち，その日は訪れた。袋の中の暗銀が低くうなるように震え，漆黒のなかでより暗き台が部屋の中央に浮かんできたのだ。

   ミトは台の上に暗銀の板を乗せると，鎚で打った。板とともにその身は激しく震え，皮膚が裂けた。それでも打ちつづけた。板は返り血を浴びながらやがてその姿を真円に変えていく。

   ついにそれは，全ての光を飲み込む，黒き真円の盾となった。これに触れれば，もはや人として生きることはかなわぬだろう。しばしの逡巡ののち，ミトは盾の面に触れた。

   全身の血，肉，骨が全て粉々になるほどの衝撃があった。盾は手の平に吸いつき離れず，その痛みにミトはのたうちまわった。盾は手の肉を食いやぶり，指や骨をえぐりながら，手の甲に再び現れると，そこに留まった。

   痛みが治まることはなく，同時に黒龍への怒りが激しくわきあがった。あの邪悪が存在することが許せなかった。何を犠牲にしても必ず滅ぼす。その意志はミトの身体を走らせていた。

** 8
   思えば黒龍に敗れたとき，自分は祝福の教えを捨て去っていたのかもしれない。

   あの煙くすぶる小屋で，槍の先に突き刺さった導師の亡骸を見たとき，ミトは剣を抜いた。

   気がつくと足元にはばらばらになった肉の山があった。

   血糊のついた剣にうつった姿に，ミトはかつて山賊だった頃の自分を見た。

   世界は自分から何もかも奪ってゆく。だから奪ってやる。

   その気持ちは捨て去ったはずだった。

   だがそれは自身の奥底で眠っていただけで，ふとしたきっかけで目覚めた。

   都の僧侶が自分に向けたもの，その信者が自分に向けたもの。憎しみ，軽蔑，殺意。

   自分が持つものはそれらと何らかわらなかった。

   どれほど鍛錬し，どれほど邪悪を滅ぼそうと，自分の心は，あの山賊の頃，そして幼い頃から変わっていなかった。

   世界とは自分から奪っていくもので，自分とはその世界から奪うもの。

   ならば，いまの自分にできることは，ただひとつ。

   黒龍の命を奪うことだけだ。

** 9
   黒龍の塔は以前のように邪悪に満ちていたが，もはやミトを押しとどめることはできなかった。敵が武器をふるい，それがこちらの盾に触れると，相手の身体は粉微塵になった。真円の盾は受けた力の分，相手を傷つける武器。奪おうとすればするほど，より多く奪われるのだ。滑稽ではないか。

   敵の屍を超え，階を踏み，忘れもしない場所へとたどりついた。塔の頂上。そこに座す黒き塊が首をもたげると，翼を広げ，世界の隅々まで響きわたるような雄叫びをあげ飛び立った。

   その動き，その仕草。攻撃の予兆。敗れし日以来，その姿を悪夢として見ない日はなかった。それゆえ，黒龍のすべてをミトは読んだ。毒の息吹。地割れ。羽ばたきの暴風。酸の嵐。邪悪なる者の召喚。影への分身。視界を奪う霧。それらすべてを盾で返し，黒龍を追いつめていった。

   戦いは果てしなく続いた。塔はその衝撃に耐えられず崩れ始めたが，なおもミトは黒龍を捉えつづけ，ついにその巨大な身体は地面に伏した。肉は裂け，骨ばかりのその身体はミトの写し身のようだった。

   もはや黒龍に何も奪う力はない。鱗がはがれ，むき出しとなった心臓に，ミトは長きにわたり使ってきた鋼の刃をつきたてた。

   その瞬間，この世界に残った最後の陽が消えたのを感じた。同時に，ミトは刃をとおして黒龍の意思を知った。

   かつて力を失った太陽は姿を隠した。そしてその姿を黒龍に変え，炎を蓄えつづけた。来たるべき再生の日に向けて。だが黒龍は斃れ，本来の姿である太陽も永遠に失われた。光なき世界はやがて滅びを迎えるだろう。

   世界に全てを奪われた戦士は，終にその世界を奪った。最後の支えを失ったその身体は揺らぎ，崩れ落ちる。そして暗闇の支配するなかでよみがえってきたのは，あの朽ちかけた教会で，自分もその平穏を得られるのかを聖女に問う姿だった。

  <br>

  <br>

  -- 了 --

  <br>

  <br>

  もうひとつの結末を知りたい方は，ブランチをanotherに切り替えてください。

  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]


